### ISSUE TITLE
Settings > management  address Error 

### ISSUE THREAD

**Issue by HonamSong** [bnhf/openvpn-admin-plus#52]
Hi! hnhf

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/77316601/221105432-4599e8ff-7d80-4209-9030-5249c8dc831d.png">

If you change the Management Address in the Settings field, an error occurs as shown below.
There is an address that can be connected normally.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/77316601/221105131-87b73437-8f6f-4439-8f8c-950427edca3c.png">

**Comment by bnhf** [comment]
@HonamSong 

Getting the Management Interface (MI) setup is something that can trip people up. The first thing you need to do is get the OpenVPN directive for enabling the MI into your server.conf file.

The easiest way to do that is to use Configuration - OpenVPN Config in the WebUI. You need to run through this once in full to get the database setup with your specific values. Many of the default values will be correct, but be sure to update the ones that aren't. Changes are made behind-the-scenes to the way the log file is configured here too.

For a typical installation the Management directive should be set to 172.17.0.1 2080 (note the colon is not used here). This is the address of the default docker gateway, and is the most secure way to communicate between the docker-based WebUI, and a host-based installation of OpenVPN.

Once that's done, and OpenVPN has been restarted or the host server rebooted, you can then update Configuration - Settings with 172.17.0.1:2080, to communicate with OpenVPN via that same default docker gateway.

**Comment by bnhf** [comment]
@HonamSong 

Also, thanks for pointing out the panic.go when using a hostname.domain in this field. Docker can be unreliable resolving hostnames for the host network, which is probably why I rarely test with them -- but we certainly want field data to be gracefully handled. So, I'll put some proper error handling in there.

See my previous comment for how to get things going using the default Docker gateway IP as the address for the Management Interface.

**Comment by HonamSong** [comment]
> @HonamSong
> 
> Getting the Management Interface (MI) setup is something that can trip people up. The first thing you need to do is get the OpenVPN directive for enabling the MI into your server.conf file.
> 
> The easiest way to do that is to use Configuration - OpenVPN Config in the WebUI. You need to run through this once in full to get the database setup with your specific values. Many of the default values will be correct, but be sure to update the ones that aren't. Changes are made behind-the-scenes to the way the log file is configured here too.
> 
> For a typical installation the Management directive should be set to 172.17.0.1 2080 (note the colon is not used here). This is the address of the default docker gateway, and is the most secure way to communicate between the docker-based WebUI, and a host-based installation of OpenVPN.
> 
> Once that's done, and OpenVPN has been restarted or the host server rebooted, you can then update Configuration - Settings with 172.17.0.1:2080, to communicate with OpenVPN via that same default docker gateway.

@bnhf
Thank you for your confirmation.

But,  My problem is below.
 1.  Appears normally if the client is not connected.
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/77316601/221725792-8ffbdad5-9007-48af-9acf-7b1e7afbef4e.png">

 2. But, 500Error Return when client connects
<img width="705" alt="image" src="https://user-images.githubusercontent.com/77316601/221726282-4e6938c2-ba03-40c9-8f6c-afec4e6ae235.png">

And, pivpn-tap-web-ui process log is below.
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/77316601/221726558-a0a511f5-88bb-4ddb-bde3-33fce922ba11.png">

 3. If the client disconnects, the screen will display normally within a few seconds.


 My configuration  server.conf =>  172.17.0.1 2080 and MI setup config => 172.17.0.1:2080

Do you understand my problem?
Is there something I'm missing?

**Comment by bnhf** [comment]
@HonamSong 

The answer is right in your screenshot of the Status page. OpenVPN 2.5.x or higher is required for this WebUI, and you are using 2.4.7:

![screenshot-github com-2023 02 27-18_51_11](https://user-images.githubusercontent.com/41088895/221732592-dd0bcdfc-aea2-4ae7-9ddf-bcf1b76fde7e.png)

There are several ways to upgrade OpenVPN if the repository used by your distro installs 2.4.7. You may be able to do it through backports, or check the OpenVPN website for information on your options. 2.5.x includes many enhancements and is well worth installing. 2.6.x is out now too, though I haven't had a chance to test it.

**Comment by HonamSong** [comment]
@bnhf 
OK!  Thank you so mach! 
I`ll try Change the version and test.

**Comment by HonamSong** [comment]
@bnhf
After changing the version it displays fine.
 Thank you so much for your help.
