### ISSUE TITLE
Port 8080 is not listening

### ISSUE THREAD

**Issue by Luccio96** [bnhf/openvpn-admin-plus#53]
Hi,
I've installed the container from the stack and successfully deployed.
Now the contain is started but I can't open the gui at ip:8080, also checked the listening port on the server and the 8080 is missing.

I'm using debian 11 and my openvpn server is currently working on the default path "/etc/openvpn/"

**Comment by bnhf** [comment]
@Luccio96 

Assuming you're using Portainer, what is showing at the end of your log after the container launches. For example, mine shows:

```console
2023/04/08 13:10:43.943 [I] [asm_amd64.s:1581]  http server Running on http://:8080
```

Also what's showing, as far as the openvpn-admin-plus container is concerned, in the Containers section of Portainer?

![screenshot-nuc10-pc2-2023 04 14-07_21_33](https://user-images.githubusercontent.com/41088895/232055679-c317e8ba-ffea-424c-8327-2accb2a09749.png)

Is it possible that you already have something running on port 8080?

**Comment by Luccio96** [comment]
Hi @bnhf 

This is my logs:

`2023-04-17T07:03:41.026873581Z TERM environment variable not set.
2023-04-17T07:03:41.064898127Z OpenVPN directory set to: /etc/openvpn
2023-04-17T07:03:41.064927584Z Working directory set to: /opt
2023-04-17T07:03:41.136755920Z PiVPN server set to: server_5WvzCbfmkb2jPw63 server_X194SFMGqcUxbZkB
2023-04-17T07:03:41.136869622Z Working directory set to: /opt/openvpn-gui-tap
2023-04-17T07:03:41.173742736Z sed: -e expression #1, char 97: unterminated `s' command`

Here the containter, as it shows it's running and I don't have anything running on port 8080.

![Senza titolo](https://user-images.githubusercontent.com/41821623/232410262-ae84cc5c-4b05-4bf1-bc82-df6711c0d2dd.png)

**Comment by Luccio96** [comment]
@bnhf 

I did it but still the same errors and the port is not listening, tried also to change the port...
As I see from Image info the created date is 2023-01-11, is there a newer one?

<img width="1071" alt="Screenshot 2023-04-17 alle 20 35 35" src="https://user-images.githubusercontent.com/41821623/232579918-93bde80f-6fbc-4409-906c-92c227e8dc1c.png">

**Comment by bnhf** [comment]
@Luccio96 

I missed it on first-look, but I believe the problem is here (from your logs):

```console
PiVPN server set to: server_5WvzCbfmkb2jPw63 server_X194SFMGqcUxbZkB
```

You seem to have two values entered for server. Only a single OpenVPN server is supported, and this value needs to match what's being used as the server name, which in turn is the name used for the server certificate and key. If you're not sure what that is, look in your current /etc/openvpn/server.conf file, and there should be a couple of directives that look like this:

```console
cert easy-rsa/pki/issued/NUC10-PC2_ae265e62-cd06-xxxx-4092-bd68-xxxxxxxxxxxx.crt
key easy-rsa/pki/private/NUC10-PC2_ae265e62-cd06-xxxx-4092-bd68-xxxxxxxxxxxx.key
```

The part including the server's name, but not including the extension, is what you want. So in the above example, the PIVPN_SERVER environment variable would be set to:

```yml
    PIVPN_SERVER=NUC10-PC2_ae265e62-cd06-xxxx-4092-bd68-xxxxxxxxxxxx
```

**Comment by Luccio96** [comment]
@bnhf 

That was the problem, after revoked the certificate the container started.
